title: Site

tabs:
  websitepages:
    label: Pagine del sito
    sections:
      pages:
        type: pages
        label: "{{ page.title }}"
        image: false
        status: all
        template:
          - home
          - listenings
          - credits
          - page
  websitesettings:
    label: Contenuti globali
    sections:
      settings:
        type: fields
        fields:
          year:
            label: Footer (copyright)
            type: number
            width: 1/4
            before: '©'
  seo:
    label: SEO del sito
    sections:
      meta:
        type: fields
        fields: 
          description:
            label: Descrizione
            type: textarea
            width: 1/2
            buttons: false
          keywords:
            label: Keywords
            type: tags
            separator: ','
            width: 1/2